import { Product } from "@/types/product";

export const accessories: Product[] = [
  {
    id: 56,
    title: "Premium Acrylic Keychain",
    slug: "premium-acrylic-keychain",
    category: "Accessories",
    categorySlug: "accessories",
    price: 199,
    originalPrice: 299,
    rating: 4.8,
    reviews: 168,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    badge: "Best Seller",
    featured: true,
    isNew: false,
    stock: 120,
    colors: ["Transparent", "Black", "White"],
    sizes: ["Standard"],
    description:
      "Premium acrylic keychain with crystal-clear finish and durable stainless steel ring.",
  },

  {
    id: 57,
    title: "Gaming Mouse Pad",
    slug: "gaming-mouse-pad",
    category: "Accessories",
    categorySlug: "accessories",
    price: 499,
    originalPrice: 699,
    rating: 4.9,
    reviews: 214,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    badge: "Trending",
    featured: true,
    isNew: true,
    stock: 65,
    colors: ["Black", "Blue"],
    sizes: ["Small", "Medium", "Large"],
    description:
      "Smooth gaming mouse pad with anti-slip rubber base and high-precision surface.",
  },

  {
    id: 58,
    title: "Premium Sticker Pack",
    slug: "premium-sticker-pack",
    category: "Accessories",
    categorySlug: "accessories",
    price: 249,
    originalPrice: 349,
    rating: 4.9,
    reviews: 281,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    badge: "Hot",
    featured: true,
    stock: 180,
    colors: ["Multicolor"],
    sizes: ["Pack of 25"],
    description:
      "Waterproof premium vinyl sticker pack with vibrant colors and long-lasting adhesive.",
  },

  {
    id: 59,
    title: "Custom Round Badge",
    slug: "custom-round-badge",
    category: "Accessories",
    categorySlug: "accessories",
    price: 149,
    originalPrice: 249,
    rating: 4.7,
    reviews: 132,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    badge: "Featured",
    featured: true,
    stock: 220,
    colors: ["White", "Black", "Multicolor"],
    sizes: ["44 mm", "58 mm"],
    description:
      "High-quality custom round badge with vibrant print and durable metal pin backing.",
  },

  {
    id: 60,
    title: "Personalized Fridge Magnet",
    slug: "personalized-fridge-magnet",
    category: "Accessories",
    categorySlug: "accessories",
    price: 299,
    originalPrice: 399,
    rating: 5.0,
    reviews: 194,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    badge: "Customize",
    featured: true,
    isNew: true,
    stock: 95,
    colors: ["White", "Black"],
    sizes: ["Square", "Round"],
    description:
      "Create personalized fridge magnets with your own photos, artwork, or custom designs.",
  },
];