import { Product } from "@/types/product";

export const bags: Product[] = [
  {
    id: 51,
    title: "Premium Cotton Tote Bag",
    slug: "premium-cotton-tote-bag",
    category: "Bags",
    categorySlug: "bags",
    price: 599,
    originalPrice: 799,
    rating: 4.8,
    reviews: 142,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    badge: "Best Seller",
    featured: true,
    isNew: false,
    stock: 35,
    colors: ["Black", "White", "Beige"],
    sizes: ["Standard"],
    description:
      "Premium reusable cotton tote bag with durable stitching and comfortable shoulder straps.",
  },

  {
    id: 52,
    title: "Canvas Shopping Bag",
    slug: "canvas-shopping-bag",
    category: "Bags",
    categorySlug: "bags",
    price: 699,
    originalPrice: 899,
    rating: 4.9,
    reviews: 118,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    badge: "Trending",
    featured: true,
    isNew: true,
    stock: 28,
    colors: ["Cream", "Black", "Olive"],
    sizes: ["Standard"],
    description:
      "Heavy-duty canvas shopping bag with spacious interior and premium quality fabric.",
  },

  {
    id: 53,
    title: "Laptop Sleeve Bag",
    slug: "laptop-sleeve-bag",
    category: "Bags",
    categorySlug: "bags",
    price: 999,
    originalPrice: 1299,
    rating: 4.8,
    reviews: 167,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    badge: "Premium",
    featured: true,
    stock: 22,
    colors: ["Black", "Grey"],
    sizes: ['13"', '15.6"'],
    description:
      "Protective laptop sleeve with soft inner padding and premium water-resistant fabric.",
  },

  {
    id: 54,
    title: "Gym Drawstring Bag",
    slug: "gym-drawstring-bag",
    category: "Bags",
    categorySlug: "bags",
    price: 499,
    originalPrice: 649,
    rating: 4.7,
    reviews: 95,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    badge: "Hot",
    featured: true,
    stock: 48,
    colors: ["Black", "Blue", "Red"],
    sizes: ["Standard"],
    description:
      "Lightweight gym drawstring bag ideal for sports, fitness, and everyday travel.",
  },

  {
    id: 55,
    title: "Eco Cotton Shopping Bag",
    slug: "eco-cotton-shopping-bag",
    category: "Bags",
    categorySlug: "bags",
    price: 549,
    originalPrice: 749,
    rating: 4.8,
    reviews: 132,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    badge: "Featured",
    featured: true,
    isNew: true,
    stock: 40,
    colors: ["Natural", "Black", "White"],
    sizes: ["Standard"],
    description:
      "Eco-friendly reusable shopping bag made from premium organic cotton with customizable print area.",
  },
];