import { Product } from "@/types/product";

export const caps: Product[] = [
  {
    id: 45,
    title: "Classic Baseball Cap",
    slug: "classic-baseball-cap",
    category: "Caps",
    categorySlug: "caps",
    price: 499,
    originalPrice: 699,
    rating: 4.8,
    reviews: 156,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    badge: "Best Seller",
    featured: true,
    isNew: false,
    stock: 42,
    colors: ["Black", "White", "Navy"],
    sizes: ["Free Size"],
    description:
      "Premium cotton baseball cap with adjustable strap and embroidered logo.",
  },

  {
    id: 46,
    title: "Premium Snapback Cap",
    slug: "premium-snapback-cap",
    category: "Caps",
    categorySlug: "caps",
    price: 699,
    originalPrice: 899,
    rating: 4.9,
    reviews: 121,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    badge: "Trending",
    featured: true,
    isNew: true,
    stock: 35,
    colors: ["Black", "Grey", "Red"],
    sizes: ["Free Size"],
    description:
      "Stylish snapback cap with flat visor and premium streetwear look.",
  },

  {
    id: 47,
    title: "Trucker Mesh Cap",
    slug: "trucker-mesh-cap",
    category: "Caps",
    categorySlug: "caps",
    price: 549,
    originalPrice: 749,
    rating: 4.7,
    reviews: 98,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    badge: "Hot",
    featured: true,
    stock: 28,
    colors: ["Black", "Blue", "White"],
    sizes: ["Free Size"],
    description:
      "Breathable trucker cap featuring mesh back panels for all-day comfort.",
  },

  {
    id: 48,
    title: "Dad Cap",
    slug: "dad-cap",
    category: "Caps",
    categorySlug: "caps",
    price: 449,
    originalPrice: 649,
    rating: 4.6,
    reviews: 84,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    featured: false,
    stock: 46,
    colors: ["Black", "Beige", "Olive"],
    sizes: ["Free Size"],
    description:
      "Minimal everyday dad cap with soft washed fabric and adjustable buckle.",
  },

  {
    id: 49,
    title: "Embroidered Premium Cap",
    slug: "embroidered-premium-cap",
    category: "Caps",
    categorySlug: "caps",
    price: 799,
    originalPrice: 999,
    rating: 4.9,
    reviews: 173,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    badge: "Premium",
    featured: true,
    stock: 25,
    colors: ["Black", "Navy", "White"],
    sizes: ["Free Size"],
    description:
      "Premium embroidered cap with high-quality stitching and luxury finish.",
  },

  {
    id: 50,
    title: "Streetwear Flat Cap",
    slug: "streetwear-flat-cap",
    category: "Caps",
    categorySlug: "caps",
    price: 649,
    originalPrice: 849,
    rating: 4.8,
    reviews: 139,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    badge: "Featured",
    featured: true,
    isNew: true,
    stock: 31,
    colors: ["Black", "Grey"],
    sizes: ["Free Size"],
    description:
      "Modern flat cap designed for casual and streetwear fashion lovers.",
  },
];