import { Product } from "@/types/product";

export const hoodies: Product[] = [
  {
    id: 11,
    title: "Premium Pullover Hoodie",
    slug: "premium-pullover-hoodie",
    category: "Hoodies",
    categorySlug: "hoodies",
    price: 1499,
    originalPrice: 1799,
    rating: 4.9,
    reviews: 185,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    badge: "Best Seller",
    featured: true,
    isNew: false,
    stock: 28,
    colors: ["Black", "Grey", "Navy"],
    sizes: ["M", "L", "XL"],
    description:
      "Premium fleece pullover hoodie with soft brushed interior for maximum comfort.",
  },

  {
    id: 12,
    title: "Oversized Street Hoodie",
    slug: "oversized-street-hoodie",
    category: "Hoodies",
    categorySlug: "hoodies",
    price: 1699,
    originalPrice: 1999,
    rating: 4.8,
    reviews: 142,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    badge: "Trending",
    featured: true,
    isNew: true,
    stock: 20,
    colors: ["Black", "Olive", "Cream"],
    sizes: ["M", "L", "XL"],
    description:
      "Relaxed oversized hoodie designed for modern streetwear fashion.",
  },

  {
    id: 13,
    title: "Classic Zip Hoodie",
    slug: "classic-zip-hoodie",
    category: "Hoodies",
    categorySlug: "hoodies",
    price: 1599,
    originalPrice: 1899,
    rating: 4.7,
    reviews: 118,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    badge: "Popular",
    featured: true,
    stock: 34,
    colors: ["Grey", "Black"],
    sizes: ["S", "M", "L", "XL"],
    description:
      "Classic full zip hoodie crafted with premium cotton blend fabric.",
  },

  {
    id: 14,
    title: "Minimal Logo Hoodie",
    slug: "minimal-logo-hoodie",
    category: "Hoodies",
    categorySlug: "hoodies",
    price: 1399,
    originalPrice: 1699,
    rating: 4.6,
    reviews: 94,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    featured: false,
    stock: 41,
    colors: ["White", "Black"],
    sizes: ["M", "L", "XL"],
    description:
      "Minimal design hoodie with premium quality embroidery logo.",
  },

  {
    id: 15,
    title: "Graphic Print Hoodie",
    slug: "graphic-print-hoodie",
    category: "Hoodies",
    categorySlug: "hoodies",
    price: 1799,
    originalPrice: 2099,
    rating: 4.9,
    reviews: 226,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    badge: "Hot",
    featured: true,
    isNew: true,
    stock: 16,
    colors: ["Black", "White"],
    sizes: ["M", "L", "XL"],
    description:
      "Premium graphic hoodie with vibrant high-quality front and back prints.",
  },  {
    id: 16,
    title: "Essential Winter Hoodie",
    slug: "essential-winter-hoodie",
    category: "Hoodies",
    categorySlug: "hoodies",
    price: 1599,
    originalPrice: 1899,
    rating: 4.8,
    reviews: 146,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    badge: "Featured",
    featured: true,
    isNew: false,
    stock: 35,
    colors: ["Black", "Grey", "Maroon"],
    sizes: ["S", "M", "L", "XL"],
    description:
      "Soft fleece hoodie designed to keep you warm with a premium everyday fit.",
  },

  {
    id: 17,
    title: "Heavyweight Cotton Hoodie",
    slug: "heavyweight-cotton-hoodie",
    category: "Hoodies",
    categorySlug: "hoodies",
    price: 1899,
    originalPrice: 2299,
    rating: 4.9,
    reviews: 198,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    badge: "Premium",
    featured: true,
    stock: 22,
    colors: ["Black", "Olive"],
    sizes: ["M", "L", "XL"],
    description:
      "Heavyweight cotton hoodie with thick premium fabric and oversized comfort.",
  },

  {
    id: 18,
    title: "Minimal Everyday Hoodie",
    slug: "minimal-everyday-hoodie",
    category: "Hoodies",
    categorySlug: "hoodies",
    price: 1399,
    originalPrice: 1699,
    rating: 4.7,
    reviews: 101,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    featured: false,
    stock: 48,
    colors: ["White", "Grey", "Black"],
    sizes: ["S", "M", "L"],
    description:
      "Minimal everyday hoodie with clean styling and comfortable premium fabric.",
  },

  {
    id: 19,
    title: "Anime Print Hoodie",
    slug: "anime-print-hoodie",
    category: "Hoodies",
    categorySlug: "hoodies",
    price: 1799,
    originalPrice: 2199,
    rating: 4.9,
    reviews: 267,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    badge: "Trending",
    featured: true,
    isNew: true,
    stock: 18,
    colors: ["Black", "White"],
    sizes: ["M", "L", "XL"],
    description:
      "Premium anime hoodie with vibrant HD artwork and soft brushed interior.",
  },

  {
    id: 20,
    title: "Premium Gym Hoodie",
    slug: "premium-gym-hoodie",
    category: "Hoodies",
    categorySlug: "hoodies",
    price: 1699,
    originalPrice: 1999,
    rating: 4.8,
    reviews: 139,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    badge: "Hot",
    featured: true,
    stock: 27,
    colors: ["Black", "Navy", "Dark Grey"],
    sizes: ["M", "L", "XL"],
    description:
      "Performance hoodie designed for workouts with breathable stretch fabric.",
  },
];