import { Product } from "@/types/product";

export const mugs: Product[] = [
  {
    id: 21,
    title: "Classic Ceramic Coffee Mug",
    slug: "classic-ceramic-coffee-mug",
    category: "Mugs",
    categorySlug: "mugs",
    price: 349,
    originalPrice: 449,
    rating: 4.8,
    reviews: 214,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    badge: "Best Seller",
    featured: true,
    isNew: false,
    stock: 65,
    colors: ["White", "Black"],
    description:
      "Premium ceramic coffee mug with high-quality sublimation printing.",
  },

  {
    id: 22,
    title: "Magic Color Changing Mug",
    slug: "magic-color-changing-mug",
    category: "Mugs",
    categorySlug: "mugs",
    price: 499,
    originalPrice: 649,
    rating: 4.9,
    reviews: 188,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    badge: "Trending",
    featured: true,
    isNew: true,
    stock: 42,
    colors: ["Black"],
    description:
      "Heat-sensitive magic mug that reveals your custom design.",
  },

  {
    id: 23,
    title: "Premium Couple Mug",
    slug: "premium-couple-mug",
    category: "Mugs",
    categorySlug: "mugs",
    price: 699,
    originalPrice: 899,
    rating: 4.9,
    reviews: 156,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    badge: "Popular",
    featured: true,
    stock: 30,
    colors: ["White"],
    description:
      "Beautiful matching mug set perfect for couples and gifting.",
  },

  {
    id: 24,
    title: "Office Coffee Mug",
    slug: "office-coffee-mug",
    category: "Mugs",
    categorySlug: "mugs",
    price: 399,
    originalPrice: 549,
    rating: 4.7,
    reviews: 122,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    featured: false,
    stock: 58,
    colors: ["White", "Blue"],
    description:
      "Stylish office coffee mug for everyday work and meetings.",
  },

  {
    id: 25,
    title: "Travel Coffee Mug",
    slug: "travel-coffee-mug",
    category: "Mugs",
    categorySlug: "mugs",
    price: 799,
    originalPrice: 999,
    rating: 4.8,
    reviews: 98,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    badge: "Featured",
    featured: true,
    stock: 25,
    colors: ["Black", "Silver"],
    description:
      "Insulated travel mug that keeps beverages hot or cold for hours.",
  },

  {
    id: 26,
    title: "Matte Finish Mug",
    slug: "matte-finish-mug",
    category: "Mugs",
    categorySlug: "mugs",
    price: 449,
    originalPrice: 599,
    rating: 4.7,
    reviews: 86,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    featured: false,
    stock: 38,
    colors: ["Black", "Grey"],
    description:
      "Premium matte ceramic mug with elegant modern finish.",
  },

  {
    id: 27,
    title: "Glossy Personalized Mug",
    slug: "glossy-personalized-mug",
    category: "Mugs",
    categorySlug: "mugs",
    price: 379,
    originalPrice: 499,
    rating: 4.8,
    reviews: 174,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    badge: "Hot",
    featured: true,
    stock: 54,
    colors: ["White"],
    description:
      "Glossy personalized ceramic mug with vibrant HD printing.",
  },

  {
    id: 28,
    title: "Custom Photo Mug",
    slug: "custom-photo-mug",
    category: "Mugs",
    categorySlug: "mugs",
    price: 499,
    originalPrice: 649,
    rating: 5.0,
    reviews: 247,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    badge: "Best Seller",
    featured: true,
    isNew: true,
    stock: 46,
    colors: ["White"],
    description:
      "Create your own personalized mug with your favorite photo or artwork.",
  },
];