import { Product } from "@/types/product";

export const phoneCases: Product[] = [
  {
    id: 29,
    title: "Premium Silicone Phone Case",
    slug: "premium-silicone-phone-case",
    category: "Phone Cases",
    categorySlug: "phone-cases",
    price: 599,
    originalPrice: 799,
    rating: 4.8,
    reviews: 162,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    badge: "Best Seller",
    featured: true,
    stock: 48,
    colors: ["Black", "Blue", "Red"],
    sizes: ["iPhone", "Samsung", "OnePlus"],
    description:
      "Premium soft silicone phone case with shockproof protection and comfortable grip.",
  },

  {
    id: 30,
    title: "Crystal Clear Transparent Case",
    slug: "crystal-clear-transparent-case",
    category: "Phone Cases",
    categorySlug: "phone-cases",
    price: 499,
    originalPrice: 699,
    rating: 4.7,
    reviews: 138,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    badge: "Trending",
    featured: true,
    isNew: true,
    stock: 52,
    colors: ["Transparent"],
    sizes: ["iPhone", "Samsung"],
    description:
      "Crystal clear TPU case that protects your phone while showcasing its original design.",
  },

  {
    id: 31,
    title: "Matte Finish Slim Case",
    slug: "matte-finish-slim-case",
    category: "Phone Cases",
    categorySlug: "phone-cases",
    price: 649,
    originalPrice: 849,
    rating: 4.8,
    reviews: 154,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    badge: "Featured",
    featured: true,
    stock: 41,
    colors: ["Black", "Green", "Navy"],
    sizes: ["iPhone", "Samsung", "OnePlus"],
    description:
      "Slim matte phone case with fingerprint-resistant finish and premium feel.",
  },

  {
    id: 32,
    title: "Luxury Leather Phone Case",
    slug: "luxury-leather-phone-case",
    category: "Phone Cases",
    categorySlug: "phone-cases",
    price: 899,
    originalPrice: 1199,
    rating: 4.9,
    reviews: 207,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    badge: "Premium",
    featured: true,
    stock: 26,
    colors: ["Brown", "Black"],
    sizes: ["iPhone", "Samsung"],
    description:
      "Luxury leather phone case with elegant finish and premium handcrafted quality.",
  },

  {
    id: 33,
    title: "Anime Printed Phone Case",
    slug: "anime-printed-phone-case",
    category: "Phone Cases",
    categorySlug: "phone-cases",
    price: 699,
    originalPrice: 899,
    rating: 4.9,
    reviews: 276,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    badge: "Hot",
    featured: true,
    isNew: true,
    stock: 38,
    colors: ["Black", "White"],
    sizes: ["iPhone", "Samsung", "OnePlus"],
    description:
      "HD anime printed phone case with vibrant colors and durable scratch-resistant finish.",
  },

  {
    id: 34,
    title: "Marble Designer Phone Case",
    slug: "marble-designer-phone-case",
    category: "Phone Cases",
    categorySlug: "phone-cases",
    price: 749,
    originalPrice: 949,
    rating: 4.8,
    reviews: 143,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    badge: "Trending",
    featured: true,
    stock: 34,
    colors: ["White", "Black", "Pink"],
    sizes: ["iPhone", "Samsung"],
    description:
      "Elegant marble pattern designer case with premium glossy finish.",
  },

  {
    id: 35,
    title: "Camera Protection Armor Case",
    slug: "camera-protection-armor-case",
    category: "Phone Cases",
    categorySlug: "phone-cases",
    price: 799,
    originalPrice: 999,
    rating: 4.9,
    reviews: 189,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    badge: "Best Seller",
    featured: true,
    stock: 29,
    colors: ["Black", "Blue"],
    sizes: ["iPhone", "Samsung", "OnePlus"],
    description:
      "Heavy-duty armor case with reinforced corners and camera lens protection.",
  },

  {
    id: 36,
    title: "Personalized Photo Phone Case",
    slug: "personalized-photo-phone-case",
    category: "Phone Cases",
    categorySlug: "phone-cases",
    price: 899,
    originalPrice: 1099,
    rating: 5.0,
    reviews: 315,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    badge: "Customize",
    featured: true,
    isNew: true,
    stock: 60,
    colors: ["Transparent", "Black", "White"],
    sizes: ["iPhone", "Samsung", "OnePlus"],
    description:
      "Create your own personalized phone case with your favorite photo, text, or artwork.",
  },
];