import { Product } from "@/types/product";

export const posters: Product[] = [
  {
    id: 37,
    title: "Travel Adventure Poster",
    slug: "travel-adventure-poster",
    category: "Posters",
    categorySlug: "posters",
    price: 499,
    originalPrice: 699,
    rating: 4.8,
    reviews: 184,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    badge: "Trending",
    featured: true,
    isNew: false,
    stock: 48,
    colors: ["Matte", "Glossy"],
    sizes: ["A4", "A3", "A2"],
    description:
      "Premium travel-themed wall poster printed on high-quality matte paper.",
  },

  {
    id: 38,
    title: "Anime Wall Poster",
    slug: "anime-wall-poster",
    category: "Posters",
    categorySlug: "posters",
    price: 599,
    originalPrice: 799,
    rating: 4.9,
    reviews: 236,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    badge: "Best Seller",
    featured: true,
    isNew: true,
    stock: 42,
    colors: ["Matte", "Glossy"],
    sizes: ["A4", "A3", "A2"],
    description:
      "HD anime artwork poster with vibrant colors and premium print quality.",
  },

  {
    id: 39,
    title: "Gaming Setup Poster",
    slug: "gaming-setup-poster",
    category: "Posters",
    categorySlug: "posters",
    price: 549,
    originalPrice: 749,
    rating: 4.7,
    reviews: 165,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    badge: "Hot",
    featured: true,
    stock: 40,
    colors: ["Matte"],
    sizes: ["A4", "A3"],
    description:
      "Modern gaming room poster with premium quality print and sharp details.",
  },

  {
    id: 40,
    title: "Movie Collection Poster",
    slug: "movie-collection-poster",
    category: "Posters",
    categorySlug: "posters",
    price: 649,
    originalPrice: 849,
    rating: 4.8,
    reviews: 151,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    badge: "Featured",
    featured: true,
    stock: 35,
    colors: ["Glossy"],
    sizes: ["A4", "A3", "A2"],
    description:
      "Premium movie-inspired wall poster with vibrant cinematic artwork.",
  },

  {
    id: 41,
    title: "Nature Landscape Poster",
    slug: "nature-landscape-poster",
    category: "Posters",
    categorySlug: "posters",
    price: 449,
    originalPrice: 649,
    rating: 4.9,
    reviews: 198,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    badge: "New",
    featured: true,
    isNew: true,
    stock: 56,
    colors: ["Matte"],
    sizes: ["A4", "A3", "A2"],
    description:
      "Beautiful nature landscape poster perfect for home and office décor.",
  },

  {
    id: 42,
    title: "Minimal Quote Poster",
    slug: "minimal-quote-poster",
    category: "Posters",
    categorySlug: "posters",
    price: 399,
    originalPrice: 549,
    rating: 4.6,
    reviews: 117,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    badge: "Popular",
    featured: false,
    stock: 62,
    colors: ["White", "Black"],
    sizes: ["A4", "A3"],
    description:
      "Elegant motivational quote poster with clean minimalist typography.",
  },

  {
    id: 43,
    title: "Sports Motivation Poster",
    slug: "sports-motivation-poster",
    category: "Posters",
    categorySlug: "posters",
    price: 549,
    originalPrice: 699,
    rating: 4.8,
    reviews: 143,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    badge: "Trending",
    featured: true,
    stock: 39,
    colors: ["Matte"],
    sizes: ["A4", "A3"],
    description:
      "Motivational sports wall poster for gym, office, and workout spaces.",
  },

  {
    id: 44,
    title: "Abstract Art Poster",
    slug: "abstract-art-poster",
    category: "Posters",
    categorySlug: "posters",
    price: 499,
    originalPrice: 649,
    rating: 4.7,
    reviews: 132,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    badge: "Best Seller",
    featured: true,
    stock: 44,
    colors: ["Matte", "Glossy"],
    sizes: ["A4", "A3", "A2"],
    description:
      "Modern abstract wall art poster with premium quality printing and finish.",
  },
];