import { Product } from "@/types/product";

export const tshirts: Product[] = [
  {
    id: 1,
    title: "Classic Cotton T-Shirt",
    slug: "classic-cotton-tshirt",
    category: "T-Shirts",
    categorySlug: "t-shirts",
    price: 599,
    originalPrice: 799,
    rating: 4.8,
    reviews: 152,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    badge: "Best Seller",
    featured: true,
    isNew: false,
    stock: 45,
    colors: ["Black", "White", "Navy"],
    sizes: ["S", "M", "L", "XL"],
    description:
      "Premium 180 GSM cotton t-shirt with breathable fabric and regular fit for everyday comfort.",
  },

  {
    id: 2,
    title: "Oversized Streetwear T-Shirt",
    slug: "oversized-streetwear-tshirt",
    category: "T-Shirts",
    categorySlug: "t-shirts",
    price: 799,
    originalPrice: 999,
    rating: 4.9,
    reviews: 216,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    badge: "Trending",
    featured: true,
    isNew: true,
    stock: 30,
    colors: ["Black", "Cream", "Olive"],
    sizes: ["M", "L", "XL"],
    description:
      "Relaxed oversized streetwear t-shirt made with premium heavyweight cotton.",
  },

  {
    id: 3,
    title: "Graphic Printed T-Shirt",
    slug: "graphic-printed-tshirt",
    category: "T-Shirts",
    categorySlug: "t-shirts",
    price: 699,
    originalPrice: 899,
    rating: 4.7,
    reviews: 188,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    badge: "Popular",
    featured: true,
    stock: 55,
    colors: ["White", "Black"],
    sizes: ["S", "M", "L", "XL"],
    description:
      "Premium graphic printed t-shirt with fade-resistant print quality.",
  },

  {
    id: 4,
    title: "Polo Premium T-Shirt",
    slug: "polo-premium-tshirt",
    category: "T-Shirts",
    categorySlug: "t-shirts",
    price: 899,
    originalPrice: 1099,
    rating: 4.8,
    reviews: 135,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    featured: true,
    stock: 24,
    colors: ["Blue", "White", "Black"],
    sizes: ["M", "L", "XL"],
    description:
      "Elegant premium polo t-shirt suitable for casual and office wear.",
  },

  {
    id: 5,
    title: "Vintage Washed T-Shirt",
    slug: "vintage-washed-tshirt",
    category: "T-Shirts",
    categorySlug: "t-shirts",
    price: 849,
    originalPrice: 1099,
    rating: 4.9,
    reviews: 102,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    badge: "New",
    featured: true,
    isNew: true,
    stock: 19,
    colors: ["Grey", "Brown"],
    sizes: ["M", "L", "XL"],
    description:
      "Vintage washed premium t-shirt with soft finish and relaxed fit.",
  },

  {
    id: 6,
    title: "Minimal Logo T-Shirt",
    slug: "minimal-logo-tshirt",
    category: "T-Shirts",
    categorySlug: "t-shirts",
    price: 549,
    originalPrice: 699,
    rating: 4.6,
    reviews: 98,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    featured: false,
    stock: 60,
    colors: ["Black", "White"],
    sizes: ["S", "M", "L"],
    description:
      "Minimal logo everyday cotton t-shirt with soft breathable fabric.",
  },

  {
    id: 7,
    title: "Sports Performance T-Shirt",
    slug: "sports-performance-tshirt",
    category: "T-Shirts",
    categorySlug: "t-shirts",
    price: 899,
    originalPrice: 1199,
    rating: 4.8,
    reviews: 174,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    badge: "Hot",
    featured: true,
    stock: 34,
    colors: ["Black", "Blue"],
    sizes: ["M", "L", "XL"],
    description:
      "Quick dry sports t-shirt with moisture-wicking premium fabric.",
  },

  {
    id: 8,
    title: "Anime Graphic T-Shirt",
    slug: "anime-graphic-tshirt",
    category: "T-Shirts",
    categorySlug: "t-shirts",
    price: 749,
    originalPrice: 949,
    rating: 4.9,
    reviews: 312,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    badge: "Trending",
    featured: true,
    stock: 40,
    colors: ["Black", "White"],
    sizes: ["S", "M", "L", "XL"],
    description:
      "Premium anime printed t-shirt with vibrant high-quality print.",
  },

  {
    id: 9,
    title: "Heavyweight Cotton T-Shirt",
    slug: "heavyweight-cotton-tshirt",
    category: "T-Shirts",
    categorySlug: "t-shirts",
    price: 999,
    originalPrice: 1299,
    rating: 4.8,
    reviews: 84,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    featured: false,
    stock: 18,
    colors: ["Olive", "Black"],
    sizes: ["M", "L", "XL"],
    description:
      "Heavyweight premium cotton t-shirt with durable stitching and oversized fit.",
  },

  {
    id: 10,
    title: "Premium Round Neck T-Shirt",
    slug: "premium-round-neck-tshirt",
    category: "T-Shirts",
    categorySlug: "t-shirts",
    price: 649,
    originalPrice: 849,
    rating: 4.7,
    reviews: 145,
    image: "/products/placeholder.jpg",
    images: [
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
      "/products/placeholder.jpg",
    ],
    badge: "Featured",
    featured: true,
    stock: 52,
    colors: ["White", "Black", "Maroon"],
    sizes: ["S", "M", "L", "XL"],
    description:
      "Premium round neck cotton t-shirt perfect for everyday casual wear.",
  },
];